[package]
name = "primitives"
version = "2.0.0-beta.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.sp-core]
default-features = false
git = 'https://github.com/gluwa/substrate.git'
rev = '57cab2f30bcc5343771c8bc763dd6c9c9e10f0a8'
version = '4.1.0-dev'
